version: "3.9"

services:
  php_service:
    build: ./php_service
    container_name: php_service
    ports:
      - "8080:8080"
    volumes:
      - ./php_service:/var/www/html
    depends_on:
      - mysql_service

  mysql_service:
    build: ./mysql_service
    container_name: mysql_service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_service/se.sql:/docker-entrypoint-initdb.d/se.sql

volumes:
  mysql_data:
