version: "3.9"

services:
  surpex:
    build: ./surpex
    container_name: surpex
    ports:
      - "8080:8080"
    volumes:
      - ./surpex:/var/www/html
    depends_on:
      - surpex_db

  surpex_db:
    build: ./surpex_db
    container_name: surpex_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./surpex_db/se.sql:/docker-entrypoint-initdb.d/se.sql

volumes:
  mysql_data:

